### ISSUE TITLE
docker-compose build php container failed, wrong php/mcrypt version

### ISSUE THREAD

**Issue by Jannnnnn** [Smolevich/demo-mongo-application#11]
Run `docker-compose build --force-rm php`

Error: `pecl/mcrypt requires PHP (version >= 7.2.0, version <= 7.4.0, excluded versions: 7.4.0), installed version is 7.4.3-dev`

My temporary fix is to use `mcrypt-1.0.3`

**Comment by Smolevich** [comment]
Fixed #12
